services:
  - type: web
    name: nexora-backend
    env: node
    plan: free

    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production

      - key: HOST
        value: 0.0.0.0

      - key: MYSQL_HOST
        value: calcium.scnservers.net

      - key: MYSQL_PORT
        value: "3306"

      - key: MYSQL_DATABASE
        value: dynamicw_dynamicworld

      - key: MYSQL_USER
        value: dynamicw_dynamicworlddata

      - key: MYSQL_PASSWORD
        sync: false

      - key: MYSQL_CONNECTION_TIMEOUT_MS
        value: "10000"

      - key: API_BASE_URL
        value: https://backend-3mp3.onrender.com/api

      - key: CORS_ORIGIN
        sync: false